name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGlCFegAWsDP7z_j8Q.OGV2d-aCRxc"
            index: 0
          - recaptcha_token: "thr1.AAAAAGlCFe8qcTJMWc6P5w.Dbe7gDLNv6o"
            index: 1
          - recaptcha_token: "thr1.AAAAAGlCFfjLIGDdjV5gpw.oG7udam5wBM"
            index: 2
          - recaptcha_token: "thr1.AAAAAGlCFgEIje1twhSV7g.8DFqmaCMkdk"
            index: 3
          - recaptcha_token: "thr1.AAAAAGlCFtacuu_Neo17Sw.80LFtC088JA"
            index: 4
          - recaptcha_token: "thr1.AAAAAGlCFt37s-wuOHYC_Q.NHDkPCY5w6M"
            index: 5
          - recaptcha_token: "thr1.AAAAAGlCFuXl_Dpc3TI5xw.xyvx7S-6YDM"
            index: 6
          - recaptcha_token: "thr1.AAAAAGlCFuyEWwWUjpzOiA.KQzpsW34xIE"
            index: 7
          - recaptcha_token: "thr1.AAAAAGlCF0SEC_co6rHFEg.CzObIFA8lg8"
            index: 8
          - recaptcha_token: "thr1.AAAAAGlCF1aeJMjdZfhDGA.xg5-y7W4gjQ"
            index: 9
          - recaptcha_token: "thr1.AAAAAGlCF2D7YtvfZ-w8bg.xJZAknWVEas"
            index: 10

    steps:
      - name: üß© Checkout repo
        uses: actions/checkout@v4

      - name: üßπ Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Instalar dependencias
        run: npm install

      - name: üöÄ Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "üëΩ"
