name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGk4eSsZ4gKc5myLsg.qZU7n-LXn-g"
            index: 0
          - recaptcha_token: "thr1.AAAAAGk4eTX_krKuuvo8sA.d0kW9Ihj5S0"
            index: 1
          - recaptcha_token: "thr1.AAAAAGk4eTswr4UPXRHGOw.ZfW32gbX7Cg"
            index: 2
          - recaptcha_token: "thr1.AAAAAGk4eUG5lkQjNv5dMA.V-OCRSStIjA"
            index: 3
          - recaptcha_token: "thr1.AAAAAGk4eUzJWtkX_wvFIg.UId9-V_FD5w"
            index: 4
          - recaptcha_token: "thr1.AAAAAGk4eVRc0PZW4B2efA._yDTt1lhcYk"
            index: 5
          - recaptcha_token: "thr1.AAAAAGk4eVyJlvwvmJyzGQ.FvWQJPPA5dY"
            index: 6
          - recaptcha_token: "thr1.AAAAAGk4eWSR0ZDR2-oDBg.b40IxQI6EnE"
            index: 7
          - recaptcha_token: "thr1.AAAAAGk4eW3t6-y28U1Jxg.XFAVxXCd4j4"
            index: 8
          - recaptcha_token: "thr1.AAAAAGk4eXSnBZ1RltxeYQ.OIk8LnlRrQc"
            index: 9
          - recaptcha_token: "thr1.AAAAAGk4eX0omjkkTg78Wg.n4FahCq9Pcw"
            index: 10

    steps:
      - name: üß© Checkout repo
        uses: actions/checkout@v4

      - name: üßπ Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Instalar dependencias
        run: npm install

      - name: üöÄ Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "üëΩ"
